### ISSUE TITLE
Looking for clarification on "discord_edgelist_covid_ship" function

### ISSUE THREAD

**Issue by nisargvp** [EpiModel/EpiModelCOVID#1]
Hello Sam,
This is  Nisarg, part of the group adapting your cruise code for the hospital context. I was looking for your help to provide an insight into why "nw = 1" in line 221 of "mod-infection.R" , within the "discord_edgelist_covid_ship" function? 

I noticed it did not seem to affect the outcome for the patient/ healthcare worker parameters (different parameter values for # of patients, health care workers & rooms compared to the cruise ship code) if I change it to "nw" or "nw=2" since the infection function is dependent on the network selected on the discordant edge.*

Thanks a lot for your help,
Nisarg

*edit: changing it to nw or nw=2 did have an effect on the cruise ship code. limiting the simulation output to both crew and passengers & only passengers respectively.

**Comment by smjenness** [comment]
Sorry I did not see this earlier comment....
