### ISSUE TITLE
Fix nwstats calculation to use modern approach

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModelCOVID#15]
See implementation in corporate moduleset. 

Updates needed for init and simnet modules for ContactTrace

Remove bespoke calc_nwstats functions in package.

**Comment by AdrienLeGuillou** [comment]
I am a bit unsure about the path you want me to take for this one:

- copy paste (and adapt if needed) the code in the corparate moduleset to ContactTrace 
- make said code into a function and call it in both case
- same as above but with the function in core EpiModel so to have it available as well for EpiModelHIV

**Comment by smjenness** [comment]
For now, just copy, paste and adapt (and then test).
