### ISSUE TITLE
Mismatch in positional and unique IDs using get_partners() function

### ISSUE THREAD

**Issue by kristinharrington** [EpiModel/EpiModelCOVID#19]
When filtering for eligible IDs for case investigation (e.g., status in c(a,ic,ip)), noticing that these are not always translating into the IDs being pulled by the get_partners() for the discordant edgelist. 

For example: my idsEligCI are: 15, 657, 759, and 835. The index IDs in the discordant edgelist are 15, 659, 761, and 837. Seems like this is an issue with the positional versus unique IDs. 

Relevant code for this issue: [https://github.com/EpiModel/EpiModelCOVID/blob/ContactTrace/R/mod-intervention.R]

Lines 27-28
`      idsEligCI <- which(active == 1 & status %in% c("a", "ic", "ip") & 
                       dxStatus == 2 & is.na(eligible.case))`
Line 45
`      del_ct <- get_partners(dat, idsEligCI)`

**Comment by AdrienLeGuillou** [comment]
I'll look into this

**Comment by AdrienLeGuillou** [comment]
Hi @kristinharrington,

can you give me the script you are using for testing this and also the version of EpiModelCOVID you are in?
When trying to run the sim with the *ContactTrace* branch of EpiModelCOVID and the file *03-epi-model-calib.R* of the *main* branch in COVID-ContactTrace I get multiple errors:

- the intervention module does not return the `dat` object
- the intervention module uses a `layer` variable that is not defined

**Comment by kristinharrington** [comment]
Hi @AdrienLeGuillou,

I apologize - I just updated my lockfile again, and the version of EpiModelCOVID I have in my lockfile is version 1.1.1. I'm so sorry I didn't update this earlier!  

So I am just testing out the intervention script with a `if (at > 20) browser()` line at line 42 in my intervention script, and then comparing the `idsEligCI` vector to the index ID's in the discordant edgelist (`del_ct`). Sam found that my intervention code was missing the return of the `dat` object several weeks ago now, but that should be fixed. 

Let me know what else I can do help fix this issue!

**Comment by AdrienLeGuillou** [comment]
No worries :) I just wanted to make sure I was working on the same version before diving in.

I'll look into it now

**Comment by AdrienLeGuillou** [comment]
We checked the issue on Zoom. The problem was that (by design) `get_partners` returns the UID and not the PID of the `index`.
